VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "pcColumnHeader"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' Additional members for the column headers.
' Items are stored in the control.

Private m_sKey As String
Private m_sTag As String
Public m_lItemData As Long
Public ID As Long

